name: 'npm root install'
run: npm install latest

  node:
    permissions:
      contents: none
    name: 'nvm install-latest-npm'
    needs: [nodes]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
